fdiaz/SwiftInspector

.github/workflows/ci.yml
README.md

Reports code coverage to code cov

Add Code coverage report

---

codecov.yml

I missed updating the ignore path for the test folders now that we've reorganized the structure of the project https://github.com/fdiaz/SwiftInspector/pull/7

Update ignore paths

---

Sources/SwiftInspectorCommands/InitializerCommand.swift
Sources/SwiftInspectorCommands/StaticUsageCommand.swift
Sources/SwiftInspectorCommands/TypeConformanceCommand.swift
Sources/SwiftInspectorCommands/TypealiasCommand.swift
Sources/SwiftInspectorCore/FileManager+SwiftFiles.swift
Sources/SwiftInspectorCore/Tests/FileManagerSpec.swift

Closes https://github.com/fdiaz/SwiftInspector/issues/17

Add a helper to check if a URL is a Swift file

---

Sources/SwiftInspectorCore/InitializerAnalyzer.swift
Sources/SwiftInspectorCore/Tests/InitializerAnalyzerSpec.swift

Fixes https://github.com/fdiaz/SwiftInspector/issues/24

Handle the case where an argument label is defined

---

.github/workflows/ci.yml

Fixes https://github.com/fdiaz/SwiftInspector/issues/28

Run CI on PR and on push

---

codecov.yml

Fix ignore pattern for code coverage

---

codecov.yml

Add explicit ignore path folders to Codecov

---

README.md

I forgot to update this when I did https://github.com/fdiaz/SwiftInspector/issues/38

Update README.md badge 

---

CONTRIBUTING.md

Adding more information here to suggest _how_ to develop with this tool.

Add my workflow when working on this to CONTRIBUTING.md

---

CONTRIBUTING.md
Package.swift
Sources/SwiftInspectorAnalyzers/CachedSyntaxTree.swift
Sources/SwiftInspectorAnalyzers/Tests/FileManagerSpec.swift
Sources/SwiftInspectorAnalyzers/Tests/ImportsAnalyzerSpec.swift
Sources/SwiftInspectorAnalyzers/Tests/InitializerAnalyzerSpec.swift
Sources/SwiftInspectorAnalyzers/Tests/PropertyAnalzyerSpec.swift
Sources/SwiftInspectorAnalyzers/Tests/StaticUsageAnalyzerSpec.swift
Sources/SwiftInspectorAnalyzers/Tests/TypeConformanceAnalyzerSpec.swift
Sources/SwiftInspectorAnalyzers/Tests/TypeLocationAnalyzerSpec.swift
Sources/SwiftInspectorAnalyzers/Tests/TypealiasAnalyzerSpec.swift
Sources/SwiftInspectorAnalyzers/Tests/TypesAnalyzerSpec.swift
Sources/SwiftInspectorCommands/Tests/ImportCommandSpec.swift
Sources/SwiftInspectorCommands/Tests/InitializerCommandSpec.swift
Sources/SwiftInspectorCommands/Tests/PropertyAnalyzerCommandSpec.swift
Sources/SwiftInspectorCommands/Tests/StaticUsageCommandSpec.swift
Sources/SwiftInspectorCommands/Tests/TypeConformanceCommandSpec.swift
Sources/SwiftInspectorCommands/Tests/TypeLocationCommandSpec.swift
Sources/SwiftInspectorCommands/Tests/TypealiasCommandSpec.swift
Sources/SwiftInspectorCommands/Tests/TypesCommandSpec.swift
Sources/SwiftInspectorTestHelpers/Temporary.swift
Sources/SwiftInspectorTestHelpers/Tests/TemporarySpec.swift
Sources/SwiftInspectorTestHelpers/Tests/VisitorExecutorSpec.swift
Sources/SwiftInspectorTestHelpers/VisitorExecutor.swift
codecov.yml

Resolves #14. Best reviewed commit-by-commit. I haven't yet moved `TestTask` to this module since it doesn't have a spec file.

Create test library and introduce more test helpers

---

Sources/SwiftInspectorTestHelpers/Tests/VisitorExecutorSpec.swift
Sources/SwiftInspectorTestHelpers/VisitorExecutor.swift
Sources/SwiftInspectorVisitors/EmptyFile.swift
Sources/SwiftInspectorVisitors/GenericRequirementVisitor.swift
Sources/SwiftInspectorVisitors/Tests/EmptyFileSpec.swift
Sources/SwiftInspectorVisitors/Tests/GenericRequirementVisitorSpec.swift

Creates a visitor capable of finding and reporting generic requirements

Create GenericRequirementVisitor and spec

---

Sources/SwiftInspectorVisitors/StructVisitor.swift
Sources/SwiftInspectorVisitors/Tests/StructVisitorSpec.swift

Followup to #56. See inline comments for discussion.

StructVisitor cleanup

---

Sources/SwiftInspectorVisitors/StructVisitor.swift
Sources/SwiftInspectorVisitors/Tests/StructVisitorSpec.swift

StructVisitor should error when visiting an extension

---

Sources/SwiftInspectorVisitors/Tests/StructVisitorSpec.swift

Fixing some debt incurred in #56

Do not rely on ordering in tests

---

Sources/SwiftInspectorVisitors/FileVisitor.swift
Sources/SwiftInspectorVisitors/Tests/FileVisitorSpec.swift

More glue code! `FileVisitor` is slowly becoming more powerful

Make FileVisitor utilize ClassVisitor

---

Sources/SwiftInspectorVisitors/Tests/TypeDescriptionSpec.swift

Addresses https://github.com/fdiaz/SwiftInspector/pull/71#discussion_r570665834

Make test names read better

---

Sources/SwiftInspectorVisitors/ExtensionVisitor.swift
Sources/SwiftInspectorVisitors/FileVisitor.swift
Sources/SwiftInspectorVisitors/NestableTypeVisitor.swift
Sources/SwiftInspectorVisitors/Tests/ExtensionVisitorSpec.swift
Sources/SwiftInspectorVisitors/Tests/FileVisitorSpec.swift
Sources/SwiftInspectorVisitors/Tests/NestableTypeVisitorSpec.swift

https://github.com/fdiaz/SwiftInspector/pull/82 only got us part of the way there.
Best reviewed with whitespaces changes turned off.

Find nested typealiases and properly assign parent types

---

Sources/SwiftInspectorVisitors/NestableDeclSyntax.swift
Sources/SwiftInspectorVisitors/NestableTypeInfo.swift
Sources/SwiftInspectorVisitors/NestableTypeVisitor.swift
Sources/SwiftInspectorVisitors/Tests/NestableTypeVisitorSpec.swift

This PR adds the ability to find generic parameters defined on enums, structs, and classes.

Find generic parameters on nestable types

---

Sources/SwiftInspectorVisitors/ExtensionVisitor.swift
Sources/SwiftInspectorVisitors/NestableDeclSyntax.swift
Sources/SwiftInspectorVisitors/NestableTypeInfo.swift
Sources/SwiftInspectorVisitors/NestableTypeVisitor.swift
Sources/SwiftInspectorVisitors/PropertySyntaxVisitor.swift
Sources/SwiftInspectorVisitors/PropertyVisitor.swift
Sources/SwiftInspectorVisitors/ProtocolVisitor.swift
Sources/SwiftInspectorVisitors/Tests/ExtensionVisitorSpec.swift
Sources/SwiftInspectorVisitors/Tests/NestableTypeVisitorSpec.swift
Sources/SwiftInspectorVisitors/Tests/PropertyVisitorSpec.swift
Sources/SwiftInspectorVisitors/Tests/ProtocolVisitorSpec.swift

**Easier to review commit-by-commit**
This PR includes information about properties in both protocols / extensions and nested types.

Use properties in Protocols / Extensions and Nested Types

---

Sources/SwiftInspectorVisitors/ProtocolVisitor.swift

Traverse node.members only once

---

Sources/SwiftInspectorVisitors/Tests/TypeDescriptionSpec.swift
Sources/SwiftInspectorVisitors/TypeDescription.swift

Make TypeDescription support FunctionTypeSyntax

---

.github/workflows/ci.yml
Package@swift-5.5.swift
Sources/SwiftInspectorAnalyzers/TypeLocationAnalyzer.swift

PR to get SwiftInspector to work with Swift 5.5

Get SwiftInspector working with Xcode 13

---

Sources/SwiftInspectorVisitors/PropertyVisitor.swift
Sources/SwiftInspectorVisitors/Tests/PropertyVisitorSpec.swift

- I address this feedback from Francisco in the first commit: https://github.com/fdiaz/SwiftInspector/pull/110#discussion_r710336714
- I create a sub-visitor to simplify the code we need to write to extract the initializer and code block descriptions: https://github.com/fdiaz/SwiftInspector/pull/111#discussion_r710381745
@fdiaz cc: @dfed

Addresses feedback on recent PRs related to collecting more property information

---

README.md

Someone who finds this repository may not be as familiar as we are with the `SwiftSyntax` toolchain or the underling concepts. Let's make our project more approachable.

Update README to be more precise

---

Makefile
Package.swift
Package@swift-5.5.swift
README.md
settings.xcconfig

Thank you to @qyang-nj for figuring out how to do this!

Remove need to use 'swift package generate-xcodeproj'

---

Sources/SwiftInspectorVisitors/Tests/TypeDescriptionSpec.swift
Sources/SwiftInspectorVisitors/TypeDescription.swift

As title.
**Best reviewed commit-by-commit**

Make TypeDescription capable of understanding all types

---

Sources/SwiftInspectorVisitors/FunctionDeclarationVisitor.swift
Sources/SwiftInspectorVisitors/Tests/FunctionDeclarationVisitorSpec.swift

Resolves `// TODO: Add parameters and argument labels`.
cc @erichoracek

Capture function parameters
