codecov.yml

Code Cov was reporting code coverage on the tests themselves. Let's remove that.

Ignore Tests from code coverage

---

CONTRIBUTING.md
Sources/SwiftInspectorKit/FileManager+SwiftFiles.swift
Tests/SwiftInspectorKitTests/FileManagerSpec.swift

My current approach to traversing the file structure has a bug, it doesn't work when a subfolder has spaces.
This fixes that bug.

Fixes a bug when subfolder has spaces

---

Sources/SwiftInspectorCommands/Tests/TypealiasCommandSpec.swift
Sources/SwiftInspectorCommands/TypealiasCommand.swift
Sources/SwiftInspectorCore/Tests/TypealiasAnalyzerSpec.swift
Sources/SwiftInspectorCore/TypealiasAnalyzer.swift

**This PR is easier to review commit-by-commit**
This adds a new `typealias` command that:
- Finds all the typealias declarations in a file or folder and outputs all the names
- Has an optional `--name`  parameter to filter for a single typealias and also outputs information related to the identifiers of the typealias

Add typealias command

---

Sources/SwiftInspectorCommands/Tests/TypealiasCommandSpec.swift
Sources/SwiftInspectorCore/Tests/TypealiasAnalyzerSpec.swift

Add tests to cover for the cases @bachand pointed out here https://github.com/fdiaz/SwiftInspector/pull/10#discussion_r399408837

Add tests for multiple typealias with the same name

---

Sources/SwiftInspectorCommands/ImportsCommand.swift
Sources/SwiftInspectorCommands/InitializerCommand.swift
Sources/SwiftInspectorCommands/InspectorCommand.swift
Sources/SwiftInspectorCommands/StaticUsageCommand.swift
Sources/SwiftInspectorCommands/Tests/ImportCommandSpec.swift
Sources/SwiftInspectorCommands/Tests/InitializerCommandSpec.swift
Sources/SwiftInspectorCommands/TypealiasCommand.swift
Sources/SwiftInspectorCore/InitializerAnalyzer.swift
Sources/SwiftInspectorCore/Tests/ImportsAnalyzerSpec.swift
Sources/SwiftInspectorCore/Tests/InitializerAnalyzerSpec.swift

Adds a command to find the initializer arguments given a type name.
```
OVERVIEW: Finds information about the initializers of the specified type
USAGE: SwiftInspector initializer --path <path> --name <name> [--enable-type-only] [--disable-type-only]
OPTIONS:
--path <path>           The absolute path to the file to inspect 
--name <name>           The name of the type to look information of the
initializer 
-t, --enable-type-only/--disable-type-only
The granularity of the output (default: true)
Outputs a list of the type names by default. If disabled it outputs the
name of the parameter and the name of the type (e.g. 'foo,Int
bar,String')
-h, --help              Show help information.
```

Add initializer command

---

Sources/SwiftInspectorCommands/InitializerCommand.swift
Sources/SwiftInspectorCore/InitializerAnalyzer.swift
Sources/SwiftInspectorCore/Tests/InitializerAnalyzerSpec.swift

Work on https://github.com/fdiaz/SwiftInspector/issues/20
This fixes an edge case of when an initializer argument contains a composition of elements.

Handle the case where an initializer has a composition of types

---

Sources/SwiftInspectorCommands/InitializerCommand.swift
Sources/SwiftInspectorCommands/Tests/InitializerCommandSpec.swift
Sources/SwiftInspectorCore/Tests/InitializerAnalyzerSpec.swift

Fixes https://github.com/fdiaz/SwiftInspector/issues/20
This adds a way to filter the initializer command given a list of argument names

Add a way to filter the initializer by argument names

---

Makefile
README.md

Heavily inspired by [this article](https://nshipster.com/homebrew/#creating-a-makefile) I decided to simplify the installation and development of SwiftInspector.
We might want to put this in Homebrew at some point, but not today.

Add Makefile to simplify setup

---

Sources/SwiftInspectorCommands/Tests/TypeLocationCommandSpec.swift
Sources/SwiftInspectorCommands/TypeLocationCommand.swift
Sources/SwiftInspectorCore/Tests/InitializerAnalyzerSpec.swift
Sources/SwiftInspectorCore/Tests/TypeLocationAnalyzerSpec.swift
Sources/SwiftInspectorCore/TypeLocationAnalyzer.swift
Sources/SwiftInspectorCore/TypealiasAnalyzer.swift

This PR is best reviewed in files changed view.
This command allows you to find the lines of a file that contain a type declaration.
```
OVERVIEW: Finds the line numbers on which a type is declared
USAGE: SwiftInspector type-location --name <name> --path <path>
OPTIONS:
--name <name>           The name of the type to find the location of 
This may be a enum, class, struct, or protocol.
--path <path>           The absolute path to the file to inspect 
-h, --help              Show help information.
```
This command can be useful if you are trying to move code. It allows you to find a type definition within a file and extract it easily.
The command returns the start and end index of the type. So if your type starts on line 2 (0 indexed) and ends on line 4, you will get back.
```
$ …
```

Add type location command

---

.github/workflows/ci.yml
Package.resolved
Package.swift
README.md
Sources/SwiftInspectorCore/ImportsAnalyzer.swift
Sources/SwiftInspectorCore/InitializerAnalyzer.swift
Sources/SwiftInspectorCore/StaticUsageAnalyzer.swift
Sources/SwiftInspectorCore/TypeLocationAnalyzer.swift
Sources/SwiftInspectorCore/TypealiasAnalyzer.swift

Updates `ArgumentParser` and `SwiftSyntax` to be able to be used in Swift 5.2

Update swift 5.2

---

Makefile

This was failing with 
```
➜  make install
build
make: build: No such file or directory
make: *** [install] Error 1
```
This fixes that by making the `install` call the `build` defined above in this Makefile before executing the rest of the commands, while before it was just trying to execute an inexistent `build` command.

Fix dependency on build from install

---

Sources/SwiftInspectorCommands/Tests/TypeConformanceCommandSpec.swift
Sources/SwiftInspectorCommands/TypeConformanceCommand.swift
Sources/SwiftInspectorCore/Tests/TypeConformanceAnalyzerSpec.swift
Sources/SwiftInspectorCore/TypeConformanceAnalyzer.swift

**This PR is easier to review commit-by-commit**
The type-conformance command didn't return the information of the conforming type, only if the conformance existed in the file or not.
This PR introduces a way to output the names of the conforming types too.
That is, when a file contains:
```swift
protocol Some {}
final class Foo: Some { }
```
We now also return `Foo` in the output.

Add a way to return the conforming type when searching for type conformance

---

README.md

Following https://github.com/fdiaz/SwiftInspector/issues/38 we're renaming master -> main.

Update README to reflect default branch

---

Sources/SwiftInspectorCommands/InspectorCommand.swift
Sources/SwiftInspectorCommands/Tests/TypesCommandSpec.swift
Sources/SwiftInspectorCommands/TypesCommand.swift
Sources/SwiftInspectorCore/Tests/TypesAnalyzerSpec.swift
Sources/SwiftInspectorCore/TypesAnalyzer.swift

This adds an analyzer and a command for finding type information given a file. Here's what the help output looks like:
```
OVERVIEW: Finds information about types in a file
USAGE: SwiftInspector types --path <path>
OPTIONS:
--path <path>           The absolute path to the file to inspect 
-h, --help              Show help information.
```
This will return data in the following format:
```
<Type Name>,<Type>
```
where the following code:
```
import Foundation
// Foo does foo things
public struct Foo {
}
```
would output
```
Foo,struct
```

Add types analyzer

---

Sources/SwiftInspectorCommands/InspectorCommand.swift
Sources/SwiftInspectorCommands/PropertyAnalyzerCommand.swift
Sources/SwiftInspectorCommands/Tests/PropertyAnalyzerCommandSpec.swift
Sources/SwiftInspectorCore/PropertyAnalyzer.swift
Sources/SwiftInspectorCore/Tests/PropertyAnalzyerSpec.swift
Sources/SwiftInspectorCore/Tests/TypePropertiesSpec.swift

This adds a new property analyzer and command. As with the `TypeCommand` / `TypeAnalyzer` this has more information in the analyzer than it does in the command.
Here's the command
```
swift-inspector properties --help
OVERVIEW: Finds property information for the provided type
USAGE: SwiftInspector properties --name <name> --path <path>
OPTIONS:
--name <name>           The name of the type to find property information on 
This may be a enum, class, struct, or protocol.
--path <path>           The absolute path of the file to inspect 
-h, --help              Show help information.
```
This command will find property information for a provided type including:
- Type name
- Each property includes:
- Property name
- Access (public, private, internal, fileprivate)
- Scope (instance, scope)
- …

add property analyzer

---

codecov.yml

I noticed that [in this PR](https://github.com/fdiaz/SwiftInspector/pull/47) that we had some failures with code coverage dropping a tiny percentage after we migrated SwiftArgumentParser to its latest version. I think it should be possible to drop code coverage on a PR by a small amount for these types of changes in the future.
Docs: https://docs.codecov.io/docs/commit-status#threshold

Allow small code coverage drops

---

Sources/SwiftInspectorAnalyzers/ImportsAnalyzer.swift
Sources/SwiftInspectorAnalyzers/StandardAnalyzer.swift
Sources/SwiftInspectorAnalyzers/Tests/StandardAnalyzerSpec.swift
Sources/SwiftInspectorCommands/ImportsCommand.swift
Sources/SwiftInspectorVisitors/GenericRequirementVisitor.swift
Sources/SwiftInspectorVisitors/ImportSyntaxReader.swift
Sources/SwiftInspectorVisitors/Tests/ImportSyntaxReaderSpec.swift
codecov.yml

Migrates the import analyzer underlying tooling down into the Visitor module. Deletes the remainder of `ImportAnalyzer` in favor of a new `StandardAnalyzer`

ImportsAnalyzer -> ImportSyntaxReader. Also create StandardAnalyzer

---

Sources/SwiftInspectorAnalyzers/StandardAnalyzer.swift
Sources/SwiftInspectorAnalyzers/StaticUsageAnalyzer.swift
Sources/SwiftInspectorAnalyzers/Tests/StandardAnalyzerSpec.swift
Sources/SwiftInspectorAnalyzers/TypealiasAnalyzer.swift
Sources/SwiftInspectorTestHelpers/Tests/VisitorExecutorSpec.swift
Sources/SwiftInspectorTestHelpers/VisitorExecutor.swift
Sources/SwiftInspectorVisitors/ImportSyntaxReader.swift

When Is started this project I didn't realize I could use the `walk` method to accomplish a similar result than calling `visit` directly. There's an open bug for calling the `visit` method directly.
This PR removes all `SyntaxRewriter` in favor of using `SyntaxVisitor` and the `walk` method instead of `visit`.
This simplifies our reusable code so we don't need to fork so much.

Migrate SyntaxRewriter to use SyntaxVisitor instead

---

Sources/SwiftInspectorAnalyzers/Tests/StaticUsageAnalyzerSpec.swift
Sources/SwiftInspectorVisitors/ClassVisitor.swift
Sources/SwiftInspectorVisitors/EnumVisitor.swift
Sources/SwiftInspectorVisitors/ExtensionVisitor.swift
Sources/SwiftInspectorVisitors/FileVisitor.swift
Sources/SwiftInspectorVisitors/StructVisitor.swift
Sources/SwiftInspectorVisitors/Tests/ClassVisitorSpec.swift
Sources/SwiftInspectorVisitors/Tests/EnumVisitorSpec.swift
Sources/SwiftInspectorVisitors/Tests/ExtensionVisitorSpec.swift
Sources/SwiftInspectorVisitors/Tests/FileVisitorSpec.swift
Sources/SwiftInspectorVisitors/Tests/StructVisitorSpec.swift

This PR builds on top of all the prior PRs to enable the `FileVisitor` to get information about all types defined within a particular file. Note that `ClassVisitor`, `EnumVisitor`, and `ExtensionVisitor` were all built out in parallel PRs, so this PR pulls all those types together.

Enable FileVisitor to find all types

---

Sources/SwiftInspectorVisitors/ExtensionVisitor.swift
Sources/SwiftInspectorVisitors/GenericRequirementVisitor.swift
Sources/SwiftInspectorVisitors/Tests/ExtensionVisitorSpec.swift
Sources/SwiftInspectorVisitors/Tests/GenericRequirementVisitorSpec.swift
Sources/SwiftInspectorVisitors/Tests/TypeInheritanceVisitorSpec.swift
Sources/SwiftInspectorVisitors/Tests/TypeSyntax+NameExtractorSpec.swift
Sources/SwiftInspectorVisitors/TypeInheritanceVisitor.swift
Sources/SwiftInspectorVisitors/TypeSyntax+NameExtractor.swift

I realized this morning that we weren't going to properly parse `Foundation.Array` as a type. This PR creates an extension that aids with the extraction of names from a `TypeSyntax` object, and utilizes it in the places where we were previously either inspecting the `description` directly or force-casting to a `SimpleTypeIdentifierSyntax`.

Handle qualified names when parsing types

---

Sources/SwiftInspectorVisitors/ClassVisitor.swift
Sources/SwiftInspectorVisitors/EnumVisitor.swift
Sources/SwiftInspectorVisitors/ParsingTracker.swift
Sources/SwiftInspectorVisitors/StructVisitor.swift
Sources/SwiftInspectorVisitors/Tests/ClassVisitorSpec.swift
Sources/SwiftInspectorVisitors/Tests/EnumVisitorSpec.swift
Sources/SwiftInspectorVisitors/Tests/StructVisitorSpec.swift

When running this code on a complicated codebase I realized that how we'd detected that we'd finished parsing a top-level type needed work. This PR introduces a type `ParserTracker` to help encapsulate the logic we need. I'd recommend reviewing unit test changes before reviewing the code.
Note that I haven't made any changes to `ExtensionVisitor` or `ProtocolVisitor` since those types can not be nested.

Robustify determining if we've finished parsing the top-level type

---

Sources/SwiftInspectorVisitors/Tests/GenericRequirementVisitorSpec.swift
Sources/SwiftInspectorVisitors/Tests/TypeDescriptionSpec.swift
Sources/SwiftInspectorVisitors/TypeDescription.swift

This PR enables us to properly identify types with generics. In this PR I also removed the `TypeDescription` `.array` and `.dictionary` cases, since we can now canonically store these types as a `simple` type description with a generic.
I recommend viewing this PR commit by commit.

Properly handle generic arguments

---

Sources/SwiftInspectorVisitors/TypeDescription.swift

Why get it right the first time when you could get it right the second? In any case, I realized one of the doc comments didn't provide a good example. So I fixed it.

Better comment

---

Sources/SwiftInspectorVisitors/Tests/TypeDescriptionSpec.swift

When reviewing https://github.com/fdiaz/SwiftInspector/pull/73 I noticed a couple places we could be more consistent.

Small naming improvements in `TypeDescription` spec

---

Sources/SwiftInspectorVisitors/ClassVisitor.swift
Sources/SwiftInspectorVisitors/DeclarationModifierVisitor.swift
Sources/SwiftInspectorVisitors/EnumVisitor.swift
Sources/SwiftInspectorVisitors/ExtensionVisitor.swift
Sources/SwiftInspectorVisitors/ProtocolVisitor.swift
Sources/SwiftInspectorVisitors/StructVisitor.swift
Sources/SwiftInspectorVisitors/Tests/ClassVisitorSpec.swift
Sources/SwiftInspectorVisitors/Tests/EnumVisitorSpec.swift
Sources/SwiftInspectorVisitors/Tests/ExtensionVisitorSpec.swift
Sources/SwiftInspectorVisitors/Tests/ProtocolVisitorSpec.swift
Sources/SwiftInspectorVisitors/Tests/StructVisitorSpec.swift

This PR creates a `DeclarationModifierVisitor` which can be used for finding declaration modifiers (e.g. "public", "internal", "private", etc).

Get modifier information from types

---

Sources/SwiftInspectorVisitors/Tests/ImportVisitorSpec.swift

We were using `@_export import Foo` when the actual syntax is `@_exported import Foo`.
It doesn't make a difference to the tests, but it's nice when the test code would compile 🙂

Use correct attribute for exporting an import in tests

---

Makefile

If we don't kill Xcode prior to running `make develop` if `SwiftInspector.xcodeproj` is already open, Xcode will complain that it needs to reload the file from disk. On Xcode 12.4, the project reloading will never complete and it will not be possible to run unit tests again until Xcode is killed.
This PR makes killing Xcode part of the `make develop` workflow. Note that we need to wait for a short moment before opening Xcode back up after killing it.

Make 'make develop' kill Xcode

---

Sources/SwiftInspectorVisitors/ExtensionVisitor.swift

This PR helps us visit fewer nodes by only walking nodes if the types we're looking for exist.

Only walk trees in ExtensionVisitor if we know the type we're looking for exists

---

Sources/SwiftInspectorVisitors/ExtensionVisitor.swift
Sources/SwiftInspectorVisitors/FileVisitor.swift
Sources/SwiftInspectorVisitors/GenericParameterVisitor.swift
Sources/SwiftInspectorVisitors/NestableTypeVisitor.swift
Sources/SwiftInspectorVisitors/ProtocolVisitor.swift
Sources/SwiftInspectorVisitors/Tests/ExtensionVisitorSpec.swift
Sources/SwiftInspectorVisitors/Tests/FileVisitorSpec.swift
Sources/SwiftInspectorVisitors/Tests/NestableTypeVisitorSpec.swift
Sources/SwiftInspectorVisitors/Tests/ProtocolVisitorSpec.swift
Sources/SwiftInspectorVisitors/Tests/TypealiasVisitorSpec.swift
Sources/SwiftInspectorVisitors/TypealiasVisitor.swift

Also integrates `typealias`-finding into `ProtocolVisitor`, `ExtensionVisitor`, `NestableTypeVisitor`, and `FileVisitor`.

Create TypealiasVisitor and associated spec

---

Sources/SwiftInspectorVisitors/ExtensionVisitor.swift
Sources/SwiftInspectorVisitors/FileVisitor.swift
Sources/SwiftInspectorVisitors/GenericParameterVisitor.swift
Sources/SwiftInspectorVisitors/GenericRequirementVisitor.swift
Sources/SwiftInspectorVisitors/NestableTypeInfo.swift
Sources/SwiftInspectorVisitors/ProtocolVisitor.swift
Sources/SwiftInspectorVisitors/TypeDescription.swift
Sources/SwiftInspectorVisitors/TypealiasVisitor.swift

No reason not to do so that I see, and it enables consumers to store this information in `Set`s, which is helpful.

Make types Hashable

---

Sources/SwiftInspectorVisitors/AssociatedtypeVisitor.swift
Sources/SwiftInspectorVisitors/NestableTypeVisitor.swift
Sources/SwiftInspectorVisitors/Tests/NestableTypeVisitorSpec.swift

In the last commit (b5bdd1aaa8ddc54387e5cac5f2fff26a961f79c6) of https://github.com/fdiaz/SwiftInspector/pull/78, I introduced a bug. Previously the compiler was enforcing that I did this right – afterwords with the typealias we had to be a bit more careful. This PR fixes that bug, and also introduces more tests to ensure this doesn't happen again.

Do not miscategorize nested type

---

Makefile
docs/Releasing.md

Thanks to @keith for writing [this](https://www.smileykeith.com/2021/03/03/editing-rpaths/) amazing blog post that helped create this portable binary using SwiftSyntax.
I also added documentation on how to release a new version using this.

Create portable binary of SwiftInspector

---

Sources/SwiftInspectorVisitors/Tests/TypeDescriptionSpec.swift
Sources/SwiftInspectorVisitors/TypeDescription.swift

When I originally wrote `TypeDescription`, I took a shortcut. Instead of creating `case array` and `case dictionary` types, I encoded these types in a canonical `simple` form.
This meant that `[Int]` would be stored as `.simple(name: "Array<Int>")` and `[Int: String]` would be stored as `.simple(name: "Dictionary<Int, String>")`.
This was fine at the time. Now that I'm trying to inspect the underlying generic type, I'm realizing we need to richly encode these types.
This PR introduces `case array` and `case dictionary`. I've included comments that highlight a different possible approach – curious to get the reviewers' thoughts.

Encode rich Array and Dictionary information in TypeDescription

---

Sources/SwiftInspectorVisitors/AssociatedtypeVisitor.swift
Sources/SwiftInspectorVisitors/ExtensionVisitor.swift
Sources/SwiftInspectorVisitors/NestableDeclSyntax.swift
Sources/SwiftInspectorVisitors/NestableTypeInfo.swift
Sources/SwiftInspectorVisitors/NestableTypeVisitor.swift
Sources/SwiftInspectorVisitors/ProtocolVisitor.swift
Sources/SwiftInspectorVisitors/Tests/NestableTypeVisitorSpec.swift
Sources/SwiftInspectorVisitors/TypealiasVisitor.swift

Nestable type declarations can have generic `where` requirements. This PR enables us to find those requirements.
Best reviewed commit-by-commit.

Enable nestable type visitor to find generic requirements

---

Sources/SwiftInspectorVisitors/FileVisitor.swift
Sources/SwiftInspectorVisitors/Tests/FileVisitorSpec.swift

Just missing a little bit of glue code

FileVisitor should surface inner typealiases on protocol definitions

---

Package.swift

This PR just changes what we expose on SwiftInspector externally. We don't need to expose the Commands, but exposing the Test Library can be useful since there's some niceness there for making temp files.

Expose Test Helpers as a library and stop exposing Commands

---

.github/workflows/ci.yml
Package.resolved
Package.swift
README.md
settings.xcconfig

Once this merges I'll release version `0.11.0`
Edit: OP said next release was `0.10.0` because I hadn't pulled latest `main` down!

Get SwiftInspector working with Xcode 12.5

---

Sources/SwiftInspectorVisitors/PropertySyntaxVisitor.swift
Sources/SwiftInspectorVisitors/Tests/PropertySyntaxVisitorSpec.swift

We were not handling the 
```swift
let red, green, blue: Double
let seconds: Int, hours, years: Double
```
cases correctly.
This PR adds unit tests + handles this use case.

Properties: Handle edge case

---

Sources/SwiftInspectorVisitors/PropertyVisitor.swift
Sources/SwiftInspectorVisitors/Tests/NestableTypeVisitorSpec.swift
Sources/SwiftInspectorVisitors/Tests/PropertyVisitorSpec.swift

We introduced a bug in #100 that I caught after the PR landed where a parent of a nested type that vended a property would have that property assigned to both the parent and nested type.
This PR fixes that issue. **Best reviewed in Files changed**.

Do not propagate properties to parents of nested types

---

Sources/SwiftInspectorVisitors/PropertyVisitor.swift
Sources/SwiftInspectorVisitors/Tests/PropertyVisitorSpec.swift

**Easier to review commit-by-commit**
This PR moves us into using TypeDescription for PropertyInfo instead of a simple String so we can get more information about the type.
I noticed that we were not supporting `open` properties either, so I went ahead and added those too.

[iOS] Use TypeDescription in PropertyInfo

---

Sources/SwiftInspectorVisitors/AssertionFailure.swift
Sources/SwiftInspectorVisitors/ExtensionVisitor.swift
Sources/SwiftInspectorVisitors/NestableTypeVisitor.swift
Sources/SwiftInspectorVisitors/ProtocolVisitor.swift
Sources/SwiftInspectorVisitors/Tests/ExtensionVisitorSpec.swift
Sources/SwiftInspectorVisitors/Tests/NestableTypeVisitorSpec.swift
Sources/SwiftInspectorVisitors/Tests/ProtocolVisitorSpec.swift
Sources/SwiftInspectorVisitors/TypeDescription.swift

This test method [crashes on M1 Macs](https://github.com/Quick/Nimble/blob/cfa125829821415bfaa9a43f03ee1cac6f743715/Sources/Nimble/Matchers/ThrowAssertion.swift#L124-L128), so instead of testing that we throw an assertion, this PR creates a way for us to test that we intend to assert.
Instead of calling `Swift.assertionFailure`, we'll now call `SwiftInspectorVisitors.assertionFailureOrPostNotification`, which will either assert or post a notification based on a static boolean.
The use of an static boolean with no threading barrier in this project is okay because the entire repo is single-threaded.
**We will need to merge this PR through a failing CodeCov check** because [we are expectedly not executing the `assertionFailure` line](https://app.codecov.io/gh/fdiaz/SwiftInspector/compare/106/ …

Do not use 'expect(...).to(throwAssertion())'

---

Sources/SwiftInspectorVisitors/PropertyInfo.swift
Sources/SwiftInspectorVisitors/PropertyVisitor.swift
Sources/SwiftInspectorVisitors/Tests/PropertyVisitorSpec.swift

Acting on [this piece of feedback](https://github.com/fdiaz/SwiftInspector/pull/110#discussion_r710339525) I gave to @bachand PR
This simplifies the paradigm and only gives us the information about the type rather than the equals sign and the braces sign for computed properties.
cc @dfed

Remove trivia from paradigm

---

Sources/SwiftInspectorVisitors/PropertyInfo.swift
Sources/SwiftInspectorVisitors/PropertyVisitor.swift
Sources/SwiftInspectorVisitors/Tests/PropertyInfoSpec.swift
Sources/SwiftInspectorVisitors/Tests/PropertyVisitorSpec.swift

Best reviewed in Files Changed view.
This PR builds on https://github.com/fdiaz/SwiftInspector/pull/110 to add a paradigm for properties in protocols.
We start by documenting the current behavior.
Then we add ways to strongly encode these cases into `PropertyInfo.Paradigm`.
- `var foo: Foo { get }` -> `PropertyInfo.Paradigm.protocolGetter`
- `var foo: Foo { get set }` -> `PropertyInfo.Paradigm.protocolGetterAndSetter`
`var foo: Foo { set }` is not valid Swift code.
@fdiaz cc: @dfed

Update `PropertyInfo.Paradigm` to handle properties in protocols

---

Package@swift-5.5.swift

Use exact tag for Swift 5.5

---

README.md

We support Swift 5.5 too, so let's make it clear in our README.

Update README.md to clarify support for Swift 5.4

---

Package@swift-5.5.swift

Follow-up to #123. The duplicated `Package.*.swift` files continues to trip me up. I got this right in `Package.swift`.

Missed one in #123

---

codecov.yml

Based on the [cloudcov documentation](https://docs.codecov.com/docs/commit-status#patch-status) and what @bachand mentioned [here](https://github.com/fdiaz/SwiftInspector/pull/120#issuecomment-1048231079) we should remove the patch from the coverage enforcement.

Remove patch from codecov.yml

---

Sources/SwiftInspectorVisitors/ExtensionVisitor.swift
Sources/SwiftInspectorVisitors/FileVisitor.swift
Sources/SwiftInspectorVisitors/FunctionDeclarationVisitor.swift
Sources/SwiftInspectorVisitors/NestableTypeInfo.swift
Sources/SwiftInspectorVisitors/NestableTypeVisitor.swift
Sources/SwiftInspectorVisitors/ProtocolVisitor.swift
Sources/SwiftInspectorVisitors/Tests/ExtensionVisitorSpec.swift
Sources/SwiftInspectorVisitors/Tests/FileVisitorSpec.swift
Sources/SwiftInspectorVisitors/Tests/FunctionDeclarationVisitorSpec.swift
Sources/SwiftInspectorVisitors/Tests/NestableTypeVisitorSpec.swift
Sources/SwiftInspectorVisitors/Tests/ProtocolVisitorSpec.swift

**This PR is easier to review commit-by-commit**
This PR adds information about a function name and its return type to:
- Free functions in a file
- Extensions
- Protocols
- Enums
- Classes
- Structs
We should likely add information about the argument labels and parameters, but we can do that in another PR.

Add information about function names and return types

---

codecov.yml

On a [previous PR](https://github.com/fdiaz/SwiftInspector/pull/126) we removed the [patch status](https://docs.codecov.com/docs/commit-status#patch-status) from enforcement, but we're still running it.
This PR disables patch completely since we're not gonna use it.

Disable code coverage on patch

---

Sources/SwiftInspectorVisitors/ExtensionVisitor.swift
Sources/SwiftInspectorVisitors/FunctionDeclarationVisitor.swift
Sources/SwiftInspectorVisitors/NestableTypeInfo.swift
Sources/SwiftInspectorVisitors/NestableTypeVisitor.swift
Sources/SwiftInspectorVisitors/PropertyVisitor.swift
Sources/SwiftInspectorVisitors/Tests/FunctionDeclarationVisitorSpec.swift
Sources/SwiftInspectorVisitors/Tests/NestableTypeVisitorSpec.swift
Sources/SwiftInspectorVisitors/Tests/PropertyVisitorSpec.swift

Today, our `NestableTypeVisitor` and `ExtensionVisitor` both walk the entire node tree to find properties and again to find functions. This leads to a performance hit (we're doing more than we have to!), and also led to a very real bug on `main`: our `FunctionsVisitor` attributes functions found in nested classes to the parent class type.
This PR resolves these issues by creating the `PropertyVisitor` and `FunctionVisitor` just-in-time when we encounter the expected declaration. It also tightens up the contract to make running both `PropertyVisitor` and `FunctionVisitor` over unexpected type declarations a contract violation.

Walk less of the syntax tree, and tighten up our contract for Properties and Functions visitors

---

Makefile
Package.swift

As title. Also got our script capable of releasing from an M1 Mac. This change was inspired by work done by @fdiaz elsewhere.
I tested this by running unit tests in the Package.swift project, and by running `make release` and executing that binary. I did all of this on an Intel Mac.
cc @qyang-nj

Update dependencies and binary to support releasing with Swift 5.6

---

.spi.yml

Adds support for generating documentation following https://blog.swiftpackageindex.com/posts/auto-generating-auto-hosting-and-auto-updating-docc-documentation/

Add Swift Package Index documentation

---

Sources/SwiftInspectorAnalyzers/InitializerAnalyzer.swift
Sources/SwiftInspectorVisitors/FunctionDeclarationVisitor.swift
Sources/SwiftInspectorVisitors/Tests/FunctionDeclarationVisitorSpec.swift

This PR adds support for parameter names in functions.
We were already supporting argument labels so adding this was fairly trivial.

Add support for parameter names
